// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo5v69H2rn-rF2L0zp5_HnNWzugwMZUxc',
    appId: '1:186429406770:web:2afd643c29514b3d02c62b',
    messagingSenderId: '186429406770',
    projectId: 'sudo-c7d1c',
    authDomain: 'sudo-c7d1c.firebaseapp.com',
    storageBucket: 'sudo-c7d1c.firebasestorage.app',
    measurementId: 'G-BHFQKSTXHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfVj6c4tGPzP7RPjng8biC2LvTFESss_U',
    appId: '1:186429406770:android:f33de1757fe47a7702c62b',
    messagingSenderId: '186429406770',
    projectId: 'sudo-c7d1c',
    storageBucket: 'sudo-c7d1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYR50XqWwm7vWeQXGorr9-C1rX80SGFPo',
    appId: '1:186429406770:ios:8a540f0cb9b0f6f002c62b',
    messagingSenderId: '186429406770',
    projectId: 'sudo-c7d1c',
    storageBucket: 'sudo-c7d1c.firebasestorage.app',
    iosBundleId: 'com.example.sudo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYR50XqWwm7vWeQXGorr9-C1rX80SGFPo',
    appId: '1:186429406770:ios:8a540f0cb9b0f6f002c62b',
    messagingSenderId: '186429406770',
    projectId: 'sudo-c7d1c',
    storageBucket: 'sudo-c7d1c.firebasestorage.app',
    iosBundleId: 'com.example.sudo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo5v69H2rn-rF2L0zp5_HnNWzugwMZUxc',
    appId: '1:186429406770:web:53439c93818a759402c62b',
    messagingSenderId: '186429406770',
    projectId: 'sudo-c7d1c',
    authDomain: 'sudo-c7d1c.firebaseapp.com',
    storageBucket: 'sudo-c7d1c.firebasestorage.app',
    measurementId: 'G-8S1E1HSMQW',
  );
}
